apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: example
spec:
  vaultAuthRef: auth
  refreshAfter: 30s

  type: kv-v2
  mount: secret
  path: bar

  destination:
    name: example
    create: true

  rolloutRestartTargets:
    - kind: Deployment
      name: example
