apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultDynamicSecret
metadata:
  name: example2
spec:
  vaultAuthRef: auth
  refreshAfter: 30s

  mount: database
  path: creds/default

  destination:
    name: example2
    create: true

  rolloutRestartTargets:
    - kind: Deployment
      name: example
